SELECT
    tb_life.dt_ref,
    tb_life.driverid,
    tb_life.qtde_pole_win_sprint AS qtde_pole_win_sprint_life,
    tb_life.qtde_pole_win AS qtde_pole_win_life,
    tb_life.avg_overtake_race AS avg_overtake_race_life,
    tb_life.qtde_gridpos5_sprint AS qtde_gridpos5_sprint_life,
    tb_life.avg_gridposition_race AS avg_gridposition_race_life,
    tb_life.qtde_1_gridposition_sprint AS qtde_1_gridposition_sprint_life,
    tb_life.qtde_pole_win_race AS qtde_pole_win_race_life,
    tb_life.qtde_sessions_finished_race AS qtde_sessions_finished_race_life,
    tb_life.qtd_sprint AS qtd_sprint_life,
    tb_life.qtde_sessions_finished_sprint AS qtde_sessions_finished_sprint_life,
    tb_life.qtde_1pos AS qtde_1pos_life,
    tb_life.qtde_1pos_race AS qtde_1pos_race_life,
    tb_life.qtde_points_sprint AS qtde_points_sprint_life,
    tb_life.qtde_1_gridposition_race AS qtde_1_gridposition_race_life,
    tb_life.qtde_sessions_with_overtake_race AS qtde_sessions_with_overtake_race_life,
    tb_life.qtde_sessions_with_overtake_sprint AS qtde_sessions_with_overtake_sprint_life,
    tb_life.avg_overtake AS avg_overtake_life,
    tb_life.avg_overtake_sprint AS avg_overtake_sprint_life,
    tb_life.qtd_seasons AS qtd_seasons_life,
    tb_life.qtde_gridpos5_race AS qtde_gridpos5_race_life,
    tb_life.qtde_points AS qtde_points_life,
    tb_life.qtde_points_race AS qtde_points_race_life,
    tb_life.qtde_pos5 AS qtde_pos5_life,
    tb_life.qtde_1pos_sprint AS qtde_1pos_sprint_life,
    tb_life.qtde_podios AS qtde_podios_life,
    tb_life.qtde_podios_race AS qtde_podios_race_life,
    tb_life.avg_gridposition_sprint AS avg_gridposition_sprint_life,
    tb_life.qtde_gridpos5 AS qtde_gridpos5_life,
    tb_life.avg_gridposition AS avg_gridposition_life,
    tb_life.avg_position AS avg_position_life,
    tb_life.avg_position_race AS avg_position_race_life,
    tb_life.avg_position_sprint AS avg_position_sprint_life,
    tb_life.qtd_sessions AS qtd_sessions_life,
    tb_life.qtde_sessions_finished AS qtde_sessions_finished_life,
    tb_life.qtd_race AS qtd_race_life,
    tb_life.qtde_podios_sprint AS qtde_podios_sprint_life,
    tb_life.qtde_1_gridposition AS qtde_1_gridposition_life,
    tb_life.qtd_sessions_with_points AS qtd_sessions_with_points_life,
    tb_life.qtd_sessions_with_points_race AS qtd_sessions_with_points_race_life,
    tb_life.qtd_sessions_with_points_sprint AS qtd_sessions_with_points_sprint_life,
    tb_life.qtde_sessions_with_overtake AS qtde_sessions_with_overtake_life,
    tb_life.qtde_pos5_race AS qtde_pos5_race_life,
    tb_life.qtde_pos5_sprint AS qtde_pos5_sprint_life,

    tb_last_10.qtde_pole_win_sprint AS qtde_pole_win_sprint_last10,
    tb_last_10.qtde_pole_win AS qtde_pole_win_last10,
    tb_last_10.avg_overtake_race AS avg_overtake_race_last10,
    tb_last_10.qtde_gridpos5_sprint AS qtde_gridpos5_sprint_last10,
    tb_last_10.avg_gridposition_race AS avg_gridposition_race_last10,
    tb_last_10.qtde_1_gridposition_sprint AS qtde_1_gridposition_sprint_last10,
    tb_last_10.qtde_pole_win_race AS qtde_pole_win_race_last10,
    tb_last_10.qtde_sessions_finished_race AS qtde_sessions_finished_race_last10,
    tb_last_10.qtd_sprint AS qtd_sprint_last10,
    tb_last_10.qtde_sessions_finished_sprint AS qtde_sessions_finished_sprint_last10,
    tb_last_10.qtde_1pos AS qtde_1pos_last10,
    tb_last_10.qtde_1pos_race AS qtde_1pos_race_last10,
    tb_last_10.qtde_points_sprint AS qtde_points_sprint_last10,
    tb_last_10.qtde_1_gridposition_race AS qtde_1_gridposition_race_last10,
    tb_last_10.qtde_sessions_with_overtake_race AS qtde_sessions_with_overtake_race_last10,
    tb_last_10.qtde_sessions_with_overtake_sprint AS qtde_sessions_with_overtake_sprint_last10,
    tb_last_10.avg_overtake AS avg_overtake_last10,
    tb_last_10.avg_overtake_sprint AS avg_overtake_sprint_last10,
    tb_last_10.qtd_seasons AS qtd_seasons_last10,
    tb_last_10.qtde_gridpos5_race AS qtde_gridpos5_race_last10,
    tb_last_10.qtde_points AS qtde_points_last10,
    tb_last_10.qtde_points_race AS qtde_points_race_last10,
    tb_last_10.qtde_pos5 AS qtde_pos5_last10,
    tb_last_10.qtde_1pos_sprint AS qtde_1pos_sprint_last10,
    tb_last_10.qtde_podios AS qtde_podios_last10,
    tb_last_10.qtde_podios_race AS qtde_podios_race_last10,
    tb_last_10.avg_gridposition_sprint AS avg_gridposition_sprint_last10,
    tb_last_10.qtde_gridpos5 AS qtde_gridpos5_last10,
    tb_last_10.avg_gridposition AS avg_gridposition_last10,
    tb_last_10.avg_position AS avg_position_last10,
    tb_last_10.avg_position_race AS avg_position_race_last10,
    tb_last_10.avg_position_sprint AS avg_position_sprint_last10,
    tb_last_10.qtd_sessions AS qtd_sessions_last10,
    tb_last_10.qtde_sessions_finished AS qtde_sessions_finished_last10,
    tb_last_10.qtd_race AS qtd_race_last10,
    tb_last_10.qtde_podios_sprint AS qtde_podios_sprint_last10,
    tb_last_10.qtde_1_gridposition AS qtde_1_gridposition_last10,
    tb_last_10.qtd_sessions_with_points AS qtd_sessions_with_points_last10,
    tb_last_10.qtd_sessions_with_points_race AS qtd_sessions_with_points_race_last10,
    tb_last_10.qtd_sessions_with_points_sprint AS qtd_sessions_with_points_sprint_last10,
    tb_last_10.qtde_sessions_with_overtake AS qtde_sessions_with_overtake_last10,
    tb_last_10.qtde_pos5_race AS qtde_pos5_race_last10,
    tb_last_10.qtde_pos5_sprint AS qtde_pos5_sprint_last10,

    tb_last_20.qtde_pole_win_sprint AS qtde_pole_win_sprint_last20,
    tb_last_20.qtde_pole_win AS qtde_pole_win_last20,
    tb_last_20.avg_overtake_race AS avg_overtake_race_last20,
    tb_last_20.qtde_gridpos5_sprint AS qtde_gridpos5_sprint_last20,
    tb_last_20.avg_gridposition_race AS avg_gridposition_race_last20,
    tb_last_20.qtde_1_gridposition_sprint AS qtde_1_gridposition_sprint_last20,
    tb_last_20.qtde_pole_win_race AS qtde_pole_win_race_last20,
    tb_last_20.qtde_sessions_finished_race AS qtde_sessions_finished_race_last20,
    tb_last_20.qtd_sprint AS qtd_sprint_last20,
    tb_last_20.qtde_sessions_finished_sprint AS qtde_sessions_finished_sprint_last20,
    tb_last_20.qtde_1pos AS qtde_1pos_last20,
    tb_last_20.qtde_1pos_race AS qtde_1pos_race_last20,
    tb_last_20.qtde_points_sprint AS qtde_points_sprint_last20,
    tb_last_20.qtde_1_gridposition_race AS qtde_1_gridposition_race_last20,
    tb_last_20.qtde_sessions_with_overtake_race AS qtde_sessions_with_overtake_race_last20,
    tb_last_20.qtde_sessions_with_overtake_sprint AS qtde_sessions_with_overtake_sprint_last20,
    tb_last_20.avg_overtake AS avg_overtake_last20,
    tb_last_20.avg_overtake_sprint AS avg_overtake_sprint_last20,
    tb_last_20.qtd_seasons AS qtd_seasons_last20,
    tb_last_20.qtde_gridpos5_race AS qtde_gridpos5_race_last20,
    tb_last_20.qtde_points AS qtde_points_last20,
    tb_last_20.qtde_points_race AS qtde_points_race_last20,
    tb_last_20.qtde_pos5 AS qtde_pos5_last20,
    tb_last_20.qtde_1pos_sprint AS qtde_1pos_sprint_last20,
    tb_last_20.qtde_podios AS qtde_podios_last20,
    tb_last_20.qtde_podios_race AS qtde_podios_race_last20,
    tb_last_20.avg_gridposition_sprint AS avg_gridposition_sprint_last20,
    tb_last_20.qtde_gridpos5 AS qtde_gridpos5_last20,
    tb_last_20.avg_gridposition AS avg_gridposition_last20,
    tb_last_20.avg_position AS avg_position_last20,
    tb_last_20.avg_position_race AS avg_position_race_last20,
    tb_last_20.avg_position_sprint AS avg_position_sprint_last20,
    tb_last_20.qtd_sessions AS qtd_sessions_last20,
    tb_last_20.qtde_sessions_finished AS qtde_sessions_finished_last20,
    tb_last_20.qtd_race AS qtd_race_last20,
    tb_last_20.qtde_podios_sprint AS qtde_podios_sprint_last20,
    tb_last_20.qtde_1_gridposition AS qtde_1_gridposition_last20,
    tb_last_20.qtd_sessions_with_points AS qtd_sessions_with_points_last20,
    tb_last_20.qtd_sessions_with_points_race AS qtd_sessions_with_points_race_last20,
    tb_last_20.qtd_sessions_with_points_sprint AS qtd_sessions_with_points_sprint_last20,
    tb_last_20.qtde_sessions_with_overtake AS qtde_sessions_with_overtake_last20,
    tb_last_20.qtde_pos5_race AS qtde_pos5_race_last20,
    tb_last_20.qtde_pos5_sprint AS qtde_pos5_sprint_last20,

    tb_last_40.qtde_pole_win_sprint AS qtde_pole_win_sprint_last40,
    tb_last_40.qtde_pole_win AS qtde_pole_win_last40,
    tb_last_40.avg_overtake_race AS avg_overtake_race_last40,
    tb_last_40.qtde_gridpos5_sprint AS qtde_gridpos5_sprint_last40,
    tb_last_40.avg_gridposition_race AS avg_gridposition_race_last40,
    tb_last_40.qtde_1_gridposition_sprint AS qtde_1_gridposition_sprint_last40,
    tb_last_40.qtde_pole_win_race AS qtde_pole_win_race_last40,
    tb_last_40.qtde_sessions_finished_race AS qtde_sessions_finished_race_last40,
    tb_last_40.qtd_sprint AS qtd_sprint_last40,
    tb_last_40.qtde_sessions_finished_sprint AS qtde_sessions_finished_sprint_last40,
    tb_last_40.qtde_1pos AS qtde_1pos_last40,
    tb_last_40.qtde_1pos_race AS qtde_1pos_race_last40,
    tb_last_40.qtde_points_sprint AS qtde_points_sprint_last40,
    tb_last_40.qtde_1_gridposition_race AS qtde_1_gridposition_race_last40,
    tb_last_40.qtde_sessions_with_overtake_race AS qtde_sessions_with_overtake_race_last40,
    tb_last_40.qtde_sessions_with_overtake_sprint AS qtde_sessions_with_overtake_sprint_last40,
    tb_last_40.avg_overtake AS avg_overtake_last40,
    tb_last_40.avg_overtake_sprint AS avg_overtake_sprint_last40,
    tb_last_40.qtd_seasons AS qtd_seasons_last40,
    tb_last_40.qtde_gridpos5_race AS qtde_gridpos5_race_last40,
    tb_last_40.qtde_points AS qtde_points_last40,
    tb_last_40.qtde_points_race AS qtde_points_race_last40,
    tb_last_40.qtde_pos5 AS qtde_pos5_last40,
    tb_last_40.qtde_1pos_sprint AS qtde_1pos_sprint_last40,
    tb_last_40.qtde_podios AS qtde_podios_last40,
    tb_last_40.qtde_podios_race AS qtde_podios_race_last40,
    tb_last_40.avg_gridposition_sprint AS avg_gridposition_sprint_last40,
    tb_last_40.qtde_gridpos5 AS qtde_gridpos5_last40,
    tb_last_40.avg_gridposition AS avg_gridposition_last40,
    tb_last_40.avg_position AS avg_position_last40,
    tb_last_40.avg_position_race AS avg_position_race_last40,
    tb_last_40.avg_position_sprint AS avg_position_sprint_last40,
    tb_last_40.qtd_sessions AS qtd_sessions_last40,
    tb_last_40.qtde_sessions_finished AS qtde_sessions_finished_last40,
    tb_last_40.qtd_race AS qtd_race_last40,
    tb_last_40.qtde_podios_sprint AS qtde_podios_sprint_last40,
    tb_last_40.qtde_1_gridposition AS qtde_1_gridposition_last40,
    tb_last_40.qtd_sessions_with_points AS qtd_sessions_with_points_last40,
    tb_last_40.qtd_sessions_with_points_race AS qtd_sessions_with_points_race_last40,
    tb_last_40.qtd_sessions_with_points_sprint AS qtd_sessions_with_points_sprint_last40,
    tb_last_40.qtde_sessions_with_overtake AS qtde_sessions_with_overtake_last40,
    tb_last_40.qtde_pos5_race AS qtde_pos5_race_last40,
    tb_last_40.qtde_pos5_sprint AS qtde_pos5_sprint_last40


FROM "nekt_silver"."fs_f1_driver_life" AS tb_life

INNER JOIN "nekt_silver"."fs_f1_driver_last_10" AS tb_last_10
ON tb_life.driverid = tb_last_10.driverid
AND tb_life.dt_ref = tb_last_10.dt_ref

INNER JOIN "nekt_silver"."fs_f1_driver_last_20" AS tb_last_20
ON tb_life.driverid = tb_last_20.driverid
AND tb_life.dt_ref = tb_last_20.dt_ref

INNER JOIN "nekt_silver"."fs_f1_driver_last_40" AS tb_last_40
ON tb_life.driverid = tb_last_40.driverid
AND tb_life.dt_ref = tb_last_40.dt_ref